name: mapcn_example
description: "Demonstration app for the mapcn_flutter package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  # This tells the app to use the code from your parent folder
  mapcn_flutter: 1.0.2
  latlong2: ^0.9.0
  flutter_map: ^8.2.2

flutter:
  uses-material-design: true